site_name: "Group Wiki"

repo_url: https://github.com/PotoyanGroup/GroupWiki

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
   - stylesheets/extra.css

theme:
     name: material
     palette:
         scheme: maroon
     features:
         - navigation.expand

nav:
  - GroupWiki: index.md
  - Onboarding: 
     - Group manifesto: onboarding/index.md
     - Set up your computer: onboarding/unix_list.md
     - Data Management: onboarding/data_management.md
     - Reading and Writing: onboarding/read_write.md
     - Useful Libs: sim_list.md
     - Learn SciPy: learn_scipy.md
     - Learn MD: learn_md.md
     - Learn CG: learn_cg.md
     - Learn ML: learn_ml.md
