site_name: "Seq2Ensemble"

repo_url: https://github.com/PotoyanGroup/Seq2Ensemble

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
   - stylesheets/extra.css

theme:
     name: material
     palette:
         scheme: maroon
     features:
         - navigation.expand

nav:
  - Seq2Ensemble: index.md
  - Documentation: docs.md
